package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenerateGolden runs the generator over the sample package and diffs
// against the committed golden file.
func TestGenerateGolden(t *testing.T) {
	generated, err := Generate("testdata/sample")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	want, err := os.ReadFile("testdata/sample/mnemonica_gen.go.golden")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	if string(generated) != string(want) {
		t.Errorf("generated output differs from golden:\n%s", generated)
	}
}

// TestGenerateDeterminism: a second run over a package that already has the
// generated file must produce byte-identical output (the generated file is
// excluded from its own input).
func TestGenerateDeterminism(t *testing.T) {
	first, err := Generate("testdata/sample")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	second, err := Generate("testdata/sample")
	if err != nil {
		t.Fatalf("Generate over generated package: %v", err)
	}
	if string(first) != string(second) {
		t.Error("re-running the generator over its own output changed it")
	}
}

func TestGenerateErrorDirs(t *testing.T) {
	cases := map[string]string{
		"collide":            "already declares a method",
		"foreign":            "not defined by a Define or Sub in this package",
		"noembed":            "has no embedded *User field",
		"nonstruct":          "is not a struct",
		"anon":               "the subtype must be a named struct type",
		"dynamicname":        "Sub name must be a constant string",
		"notident":           "parent must be a package-level handle",
		"broken":             "has errors",
		"absent-not-a-dir-!": "", // any error: the package dir does not exist
	}
	for dir, wantMessage := range cases {
		_, err := Generate(filepath.Join("testdata", dir))
		if err == nil {
			t.Errorf("%s: Generate succeeded, want an error", dir)
			continue
		}
		if wantMessage != "" && !strings.Contains(err.Error(), wantMessage) {
			t.Errorf("%s: error = %v, want it to contain %q", dir, err, wantMessage)
		}
	}
}

// TestGenerateRenderError reaches render's format safety net through
// Generate itself: a subtype name that is not a valid identifier produces
// unformattable output. Real sources cannot do this (the name is validated
// by compilation), so the overlay seam supplies it.
func TestGenerateRenderError(t *testing.T) {
	original, err := os.ReadFile("testdata/sample/sample.go")
	if err != nil {
		t.Fatalf("read sample: %v", err)
	}
	overlayed := bytes.Replace(original, []byte(`"Gadget"`), []byte(`"Not Valid"`), 1)
	absolute, err := filepath.Abs("testdata/sample/sample.go")
	if err != nil {
		t.Fatalf("abs path: %v", err)
	}
	_, err = generate("testdata/sample", map[string][]byte{absolute: overlayed})
	if err == nil || !strings.Contains(err.Error(), "does not format") {
		t.Fatalf("generate with an invalid subtype name error = %v, want a format error", err)
	}
}

// TestRenderErrors covers the formatting safety net and the receiver-name
// fallback, which the happy path cannot reach.
func TestRenderErrors(t *testing.T) {
	if _, err := render("p", []subtype{{varName: "xT", name: "X", child: "C", parent: "P", argsType: "not a type", embedField: "P"}}, nil); err == nil {
		t.Error("render with an unformattable args type succeeded, want a format error")
	}
	if receiver := lowerFirst(""); receiver != "x" {
		t.Errorf("lowerFirst(\"\") = %q, want %q", receiver, "x")
	}
}

// TestGenerateEmpty: a package without Sub calls still gets a valid,
// header-only file.
func TestGenerateEmpty(t *testing.T) {
	generated, err := Generate("testdata/empty")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !strings.HasPrefix(string(generated), "// Code generated by mnemonica-gen; DO NOT EDIT.\n\npackage empty\n") {
		t.Errorf("empty output = %q, want header and package only", generated)
	}
	if strings.Contains(string(generated), "func ") {
		t.Errorf("empty output declares functions: %q", generated)
	}
}

// TestRunCoversMain exercises the command wrapper: main delegates to run
// and records the exit code. It runs in a scratch package so the generated
// file lands in a temp dir, not the tree.
func TestRunCoversMain(t *testing.T) {
	scratch := t.TempDir()
	if writeErr := os.WriteFile(filepath.Join(scratch, "go.mod"), []byte("module scratch\n\ngo 1.27\n"), 0o644); writeErr != nil {
		t.Fatalf("write scratch go.mod: %v", writeErr)
	}
	if writeErr := os.WriteFile(filepath.Join(scratch, "scratch.go"), []byte("package scratch\n\ntype T struct{ X int }\n"), 0o644); writeErr != nil {
		t.Fatalf("write scratch package: %v", writeErr)
	}
	t.Chdir(scratch)
	var codes []int
	originalExit := exitFunc
	exitFunc = func(code int) {
		codes = append(codes, code)
	}
	t.Cleanup(func() {
		exitFunc = originalExit
	})

	main()
	if len(codes) != 1 || codes[0] != 0 {
		t.Fatalf("main exit codes = %v, want [0]", codes)
	}
}

// TestRunErrorAndWriteFailure covers run's failure branches.
func TestRunErrorAndWriteFailure(t *testing.T) {
	if code := run([]string{"testdata/collide"}); code != 1 {
		t.Errorf("run(collide) = %d, want 1", code)
	}

	originalWrite := writeFile
	writeFile = func(string, []byte, os.FileMode) error {
		return os.ErrPermission
	}
	t.Cleanup(func() {
		writeFile = originalWrite
	})
	if code := run([]string{"testdata/empty"}); code != 1 {
		t.Errorf("run with forced write failure = %d, want 1", code)
	}
}
