// Code generated by mnemonica-gen; DO NOT EDIT.

package sample

import (
	"context"
	"time"
)

func wireExternalToGadget(c *External, p *Gadget) {
	c.Gadget = p
}

func wireJobToGadget(c *Job, p *Gadget) {
	c.Gadget = p
}

func wireBatchedToWidget(c *Batched, p *Widget) {
	c.Widget = p
}

func wireBundledToWidget(c *Bundled, p *Widget) {
	c.Widget = p
}

func wireGadgetToWidget(c *Gadget, p *Widget) {
	c.Widget = p
}

func wireIndexedToWidget(c *Indexed, p *Widget) {
	c.Widget = p
}

func wireInferredToWidget(c *Inferred, p *Widget) {
	c.Widget = p
}

func wireLocalArgsToWidget(c *LocalArgs, p *Widget) {
	c.Widget = p
}

func wirePinnedToWidget(c *Pinned, p *Widget) {
	c.Widget = p
}

func wireTimedToWidget(c *Timed, p *Widget) {
	c.Widget = p
}

func wireVerboseToWidget(c *Verbose, p *Widget) {
	c.Widget = p
}

func init() {
	ExternalT.AttachWire(wireExternalToGadget)
	JobT.AttachWire(wireJobToGadget)
	BatchedT.AttachWire(wireBatchedToWidget)
	BundledT.AttachWire(wireBundledToWidget)
	GadgetT.AttachWire(wireGadgetToWidget)
	IndexedT.AttachWire(wireIndexedToWidget)
	InferredT.AttachWire(wireInferredToWidget)
	LocalArgsT.AttachWire(wireLocalArgsToWidget)
	PinnedT.AttachWire(wirePinnedToWidget)
	TimedT.AttachWire(wireTimedToWidget)
	VerboseT.AttachWire(wireVerboseToWidget)
}

func (gadget *Gadget) External(args string) (*External, error) {
	return ExternalT.From(gadget, args)
}

func (gadget *Gadget) ExternalCtx(ctx context.Context, args string) (*External, error) {
	return ExternalT.FromCtx(ctx, gadget, args)
}

func (gadget *Gadget) Job(args int) (*Job, error) {
	return JobT.From(gadget, args)
}

func (gadget *Gadget) JobCtx(ctx context.Context, args int) (*Job, error) {
	return JobT.FromCtx(ctx, gadget, args)
}

func (widget *Widget) Batched(args []time.Duration) (*Batched, error) {
	return BatchedT.From(widget, args)
}

func (widget *Widget) BatchedCtx(ctx context.Context, args []time.Duration) (*Batched, error) {
	return BatchedT.FromCtx(ctx, widget, args)
}

func (widget *Widget) Bundled(args struct{ Timeout time.Duration }) (*Bundled, error) {
	return BundledT.From(widget, args)
}

func (widget *Widget) BundledCtx(ctx context.Context, args struct{ Timeout time.Duration }) (*Bundled, error) {
	return BundledT.FromCtx(ctx, widget, args)
}

func (widget *Widget) Gadget(args string) (*Gadget, error) {
	return GadgetT.From(widget, args)
}

func (widget *Widget) GadgetCtx(ctx context.Context, args string) (*Gadget, error) {
	return GadgetT.FromCtx(ctx, widget, args)
}

func (widget *Widget) Indexed(args map[string]time.Duration) (*Indexed, error) {
	return IndexedT.From(widget, args)
}

func (widget *Widget) IndexedCtx(ctx context.Context, args map[string]time.Duration) (*Indexed, error) {
	return IndexedT.FromCtx(ctx, widget, args)
}

func (widget *Widget) Inferred(args string) (*Inferred, error) {
	return InferredT.From(widget, args)
}

func (widget *Widget) InferredCtx(ctx context.Context, args string) (*Inferred, error) {
	return InferredT.FromCtx(ctx, widget, args)
}

func (widget *Widget) LocalArgs(args widgetArgs) (*LocalArgs, error) {
	return LocalArgsT.From(widget, args)
}

func (widget *Widget) LocalArgsCtx(ctx context.Context, args widgetArgs) (*LocalArgs, error) {
	return LocalArgsT.FromCtx(ctx, widget, args)
}

func (widget *Widget) Pinned(args *time.Location) (*Pinned, error) {
	return PinnedT.From(widget, args)
}

func (widget *Widget) PinnedCtx(ctx context.Context, args *time.Location) (*Pinned, error) {
	return PinnedT.FromCtx(ctx, widget, args)
}

func (widget *Widget) Timed(args time.Duration) (*Timed, error) {
	return TimedT.From(widget, args)
}

func (widget *Widget) TimedCtx(ctx context.Context, args time.Duration) (*Timed, error) {
	return TimedT.FromCtx(ctx, widget, args)
}

func (widget *Widget) Verbose(args string) (*Verbose, error) {
	return VerboseT.From(widget, args)
}

func (widget *Widget) VerboseCtx(ctx context.Context, args string) (*Verbose, error) {
	return VerboseT.FromCtx(ctx, widget, args)
}
